// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: NetMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameNetMessage {

  /// <summary>Holder for reflection information generated from NetMessage.proto</summary>
  public static partial class NetMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for NetMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NetMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBOZXRNZXNzYWdlLnByb3RvEg5HYW1lTmV0TWVzc2FnZRoKVXNlci5wcm90",
            "bxoKQ2hhdC5wcm90byKGAQoKTmV0TWVzc2FnZRI7Cg1Nc2dGcm9tU2VydmVy",
            "GAEgASgLMiQuR2FtZU5ldE1lc3NhZ2UuTmV0TWVzc2FnZUZyb21TZXJ2ZXIS",
            "OwoNTXNnRnJvbUNsaWVudBgCIAEoCzIkLkdhbWVOZXRNZXNzYWdlLk5ldE1l",
            "c3NhZ2VGcm9tQ2xpZW50IqgBChROZXRNZXNzYWdlRnJvbVNlcnZlchI4Cg9V",
            "c2VyUmVnaXN0ZXJSc3AYASABKAsyHy5HYW1lTmV0TWVzc2FnZS5Vc2VyUmVn",
            "aXN0ZXJSc3ASMgoMVXNlckxvZ2luUnNwGAIgASgLMhwuR2FtZU5ldE1lc3Nh",
            "Z2UuVXNlckxvZ2luUnNwEiIKBENoYXQYAyABKAsyFC5HYW1lTmV0TWVzc2Fn",
            "ZS5DaGF0IqgBChROZXRNZXNzYWdlRnJvbUNsaWVudBI4Cg9Vc2VyUmVnaXN0",
            "ZXJSZXEYASABKAsyHy5HYW1lTmV0TWVzc2FnZS5Vc2VyUmVnaXN0ZXJSZXES",
            "MgoMVXNlckxvZ2luUmVxGAIgASgLMhwuR2FtZU5ldE1lc3NhZ2UuVXNlckxv",
            "Z2luUmVxEiIKBENoYXQYAyABKAsyFC5HYW1lTmV0TWVzc2FnZS5DaGF0YgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GameNetMessage.UserReflection.Descriptor, global::GameNetMessage.ChatReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GameNetMessage.NetMessage), global::GameNetMessage.NetMessage.Parser, new[]{ "MsgFromServer", "MsgFromClient" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameNetMessage.NetMessageFromServer), global::GameNetMessage.NetMessageFromServer.Parser, new[]{ "UserRegisterRsp", "UserLoginRsp", "Chat" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameNetMessage.NetMessageFromClient), global::GameNetMessage.NetMessageFromClient.Parser, new[]{ "UserRegisterReq", "UserLoginReq", "Chat" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class NetMessage : pb::IMessage<NetMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NetMessage> _parser = new pb::MessageParser<NetMessage>(() => new NetMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NetMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameNetMessage.NetMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetMessage(NetMessage other) : this() {
      msgFromServer_ = other.msgFromServer_ != null ? other.msgFromServer_.Clone() : null;
      msgFromClient_ = other.msgFromClient_ != null ? other.msgFromClient_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetMessage Clone() {
      return new NetMessage(this);
    }

    /// <summary>Field number for the "MsgFromServer" field.</summary>
    public const int MsgFromServerFieldNumber = 1;
    private global::GameNetMessage.NetMessageFromServer msgFromServer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameNetMessage.NetMessageFromServer MsgFromServer {
      get { return msgFromServer_; }
      set {
        msgFromServer_ = value;
      }
    }

    /// <summary>Field number for the "MsgFromClient" field.</summary>
    public const int MsgFromClientFieldNumber = 2;
    private global::GameNetMessage.NetMessageFromClient msgFromClient_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameNetMessage.NetMessageFromClient MsgFromClient {
      get { return msgFromClient_; }
      set {
        msgFromClient_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NetMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NetMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(MsgFromServer, other.MsgFromServer)) return false;
      if (!object.Equals(MsgFromClient, other.MsgFromClient)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (msgFromServer_ != null) hash ^= MsgFromServer.GetHashCode();
      if (msgFromClient_ != null) hash ^= MsgFromClient.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (msgFromServer_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MsgFromServer);
      }
      if (msgFromClient_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MsgFromClient);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (msgFromServer_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MsgFromServer);
      }
      if (msgFromClient_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MsgFromClient);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (msgFromServer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MsgFromServer);
      }
      if (msgFromClient_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MsgFromClient);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NetMessage other) {
      if (other == null) {
        return;
      }
      if (other.msgFromServer_ != null) {
        if (msgFromServer_ == null) {
          MsgFromServer = new global::GameNetMessage.NetMessageFromServer();
        }
        MsgFromServer.MergeFrom(other.MsgFromServer);
      }
      if (other.msgFromClient_ != null) {
        if (msgFromClient_ == null) {
          MsgFromClient = new global::GameNetMessage.NetMessageFromClient();
        }
        MsgFromClient.MergeFrom(other.MsgFromClient);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (msgFromServer_ == null) {
              MsgFromServer = new global::GameNetMessage.NetMessageFromServer();
            }
            input.ReadMessage(MsgFromServer);
            break;
          }
          case 18: {
            if (msgFromClient_ == null) {
              MsgFromClient = new global::GameNetMessage.NetMessageFromClient();
            }
            input.ReadMessage(MsgFromClient);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (msgFromServer_ == null) {
              MsgFromServer = new global::GameNetMessage.NetMessageFromServer();
            }
            input.ReadMessage(MsgFromServer);
            break;
          }
          case 18: {
            if (msgFromClient_ == null) {
              MsgFromClient = new global::GameNetMessage.NetMessageFromClient();
            }
            input.ReadMessage(MsgFromClient);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class NetMessageFromServer : pb::IMessage<NetMessageFromServer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NetMessageFromServer> _parser = new pb::MessageParser<NetMessageFromServer>(() => new NetMessageFromServer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NetMessageFromServer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameNetMessage.NetMessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetMessageFromServer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetMessageFromServer(NetMessageFromServer other) : this() {
      userRegisterRsp_ = other.userRegisterRsp_ != null ? other.userRegisterRsp_.Clone() : null;
      userLoginRsp_ = other.userLoginRsp_ != null ? other.userLoginRsp_.Clone() : null;
      chat_ = other.chat_ != null ? other.chat_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetMessageFromServer Clone() {
      return new NetMessageFromServer(this);
    }

    /// <summary>Field number for the "UserRegisterRsp" field.</summary>
    public const int UserRegisterRspFieldNumber = 1;
    private global::GameNetMessage.UserRegisterRsp userRegisterRsp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameNetMessage.UserRegisterRsp UserRegisterRsp {
      get { return userRegisterRsp_; }
      set {
        userRegisterRsp_ = value;
      }
    }

    /// <summary>Field number for the "UserLoginRsp" field.</summary>
    public const int UserLoginRspFieldNumber = 2;
    private global::GameNetMessage.UserLoginRsp userLoginRsp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameNetMessage.UserLoginRsp UserLoginRsp {
      get { return userLoginRsp_; }
      set {
        userLoginRsp_ = value;
      }
    }

    /// <summary>Field number for the "Chat" field.</summary>
    public const int ChatFieldNumber = 3;
    private global::GameNetMessage.Chat chat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameNetMessage.Chat Chat {
      get { return chat_; }
      set {
        chat_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NetMessageFromServer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NetMessageFromServer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(UserRegisterRsp, other.UserRegisterRsp)) return false;
      if (!object.Equals(UserLoginRsp, other.UserLoginRsp)) return false;
      if (!object.Equals(Chat, other.Chat)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (userRegisterRsp_ != null) hash ^= UserRegisterRsp.GetHashCode();
      if (userLoginRsp_ != null) hash ^= UserLoginRsp.GetHashCode();
      if (chat_ != null) hash ^= Chat.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (userRegisterRsp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UserRegisterRsp);
      }
      if (userLoginRsp_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UserLoginRsp);
      }
      if (chat_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Chat);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (userRegisterRsp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UserRegisterRsp);
      }
      if (userLoginRsp_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UserLoginRsp);
      }
      if (chat_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Chat);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (userRegisterRsp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserRegisterRsp);
      }
      if (userLoginRsp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserLoginRsp);
      }
      if (chat_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Chat);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NetMessageFromServer other) {
      if (other == null) {
        return;
      }
      if (other.userRegisterRsp_ != null) {
        if (userRegisterRsp_ == null) {
          UserRegisterRsp = new global::GameNetMessage.UserRegisterRsp();
        }
        UserRegisterRsp.MergeFrom(other.UserRegisterRsp);
      }
      if (other.userLoginRsp_ != null) {
        if (userLoginRsp_ == null) {
          UserLoginRsp = new global::GameNetMessage.UserLoginRsp();
        }
        UserLoginRsp.MergeFrom(other.UserLoginRsp);
      }
      if (other.chat_ != null) {
        if (chat_ == null) {
          Chat = new global::GameNetMessage.Chat();
        }
        Chat.MergeFrom(other.Chat);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (userRegisterRsp_ == null) {
              UserRegisterRsp = new global::GameNetMessage.UserRegisterRsp();
            }
            input.ReadMessage(UserRegisterRsp);
            break;
          }
          case 18: {
            if (userLoginRsp_ == null) {
              UserLoginRsp = new global::GameNetMessage.UserLoginRsp();
            }
            input.ReadMessage(UserLoginRsp);
            break;
          }
          case 26: {
            if (chat_ == null) {
              Chat = new global::GameNetMessage.Chat();
            }
            input.ReadMessage(Chat);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (userRegisterRsp_ == null) {
              UserRegisterRsp = new global::GameNetMessage.UserRegisterRsp();
            }
            input.ReadMessage(UserRegisterRsp);
            break;
          }
          case 18: {
            if (userLoginRsp_ == null) {
              UserLoginRsp = new global::GameNetMessage.UserLoginRsp();
            }
            input.ReadMessage(UserLoginRsp);
            break;
          }
          case 26: {
            if (chat_ == null) {
              Chat = new global::GameNetMessage.Chat();
            }
            input.ReadMessage(Chat);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class NetMessageFromClient : pb::IMessage<NetMessageFromClient>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NetMessageFromClient> _parser = new pb::MessageParser<NetMessageFromClient>(() => new NetMessageFromClient());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NetMessageFromClient> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameNetMessage.NetMessageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetMessageFromClient() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetMessageFromClient(NetMessageFromClient other) : this() {
      userRegisterReq_ = other.userRegisterReq_ != null ? other.userRegisterReq_.Clone() : null;
      userLoginReq_ = other.userLoginReq_ != null ? other.userLoginReq_.Clone() : null;
      chat_ = other.chat_ != null ? other.chat_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetMessageFromClient Clone() {
      return new NetMessageFromClient(this);
    }

    /// <summary>Field number for the "UserRegisterReq" field.</summary>
    public const int UserRegisterReqFieldNumber = 1;
    private global::GameNetMessage.UserRegisterReq userRegisterReq_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameNetMessage.UserRegisterReq UserRegisterReq {
      get { return userRegisterReq_; }
      set {
        userRegisterReq_ = value;
      }
    }

    /// <summary>Field number for the "UserLoginReq" field.</summary>
    public const int UserLoginReqFieldNumber = 2;
    private global::GameNetMessage.UserLoginReq userLoginReq_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameNetMessage.UserLoginReq UserLoginReq {
      get { return userLoginReq_; }
      set {
        userLoginReq_ = value;
      }
    }

    /// <summary>Field number for the "Chat" field.</summary>
    public const int ChatFieldNumber = 3;
    private global::GameNetMessage.Chat chat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameNetMessage.Chat Chat {
      get { return chat_; }
      set {
        chat_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NetMessageFromClient);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NetMessageFromClient other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(UserRegisterReq, other.UserRegisterReq)) return false;
      if (!object.Equals(UserLoginReq, other.UserLoginReq)) return false;
      if (!object.Equals(Chat, other.Chat)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (userRegisterReq_ != null) hash ^= UserRegisterReq.GetHashCode();
      if (userLoginReq_ != null) hash ^= UserLoginReq.GetHashCode();
      if (chat_ != null) hash ^= Chat.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (userRegisterReq_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UserRegisterReq);
      }
      if (userLoginReq_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UserLoginReq);
      }
      if (chat_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Chat);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (userRegisterReq_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UserRegisterReq);
      }
      if (userLoginReq_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UserLoginReq);
      }
      if (chat_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Chat);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (userRegisterReq_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserRegisterReq);
      }
      if (userLoginReq_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserLoginReq);
      }
      if (chat_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Chat);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NetMessageFromClient other) {
      if (other == null) {
        return;
      }
      if (other.userRegisterReq_ != null) {
        if (userRegisterReq_ == null) {
          UserRegisterReq = new global::GameNetMessage.UserRegisterReq();
        }
        UserRegisterReq.MergeFrom(other.UserRegisterReq);
      }
      if (other.userLoginReq_ != null) {
        if (userLoginReq_ == null) {
          UserLoginReq = new global::GameNetMessage.UserLoginReq();
        }
        UserLoginReq.MergeFrom(other.UserLoginReq);
      }
      if (other.chat_ != null) {
        if (chat_ == null) {
          Chat = new global::GameNetMessage.Chat();
        }
        Chat.MergeFrom(other.Chat);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (userRegisterReq_ == null) {
              UserRegisterReq = new global::GameNetMessage.UserRegisterReq();
            }
            input.ReadMessage(UserRegisterReq);
            break;
          }
          case 18: {
            if (userLoginReq_ == null) {
              UserLoginReq = new global::GameNetMessage.UserLoginReq();
            }
            input.ReadMessage(UserLoginReq);
            break;
          }
          case 26: {
            if (chat_ == null) {
              Chat = new global::GameNetMessage.Chat();
            }
            input.ReadMessage(Chat);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (userRegisterReq_ == null) {
              UserRegisterReq = new global::GameNetMessage.UserRegisterReq();
            }
            input.ReadMessage(UserRegisterReq);
            break;
          }
          case 18: {
            if (userLoginReq_ == null) {
              UserLoginReq = new global::GameNetMessage.UserLoginReq();
            }
            input.ReadMessage(UserLoginReq);
            break;
          }
          case 26: {
            if (chat_ == null) {
              Chat = new global::GameNetMessage.Chat();
            }
            input.ReadMessage(Chat);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
